name: widget_layout
description: Simple utilities for widgets to make responsive layouts in flutter
version: 0.1.0
repository: https://github.com/predatorx7/widget_layout

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.17.1
  flutter:
    sdk: flutter
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
