name: handle_test

on:
  push:
  pull_request:
  schedule:
    # runs the CI every first day of every month at 00:00 AM
    - cron: "0 0 1 * *"

jobs:
  dart:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.2
      - uses: dart-lang/setup-dart@v1

      # It is executed separatly
      - name: Removing example folder
        run: rm -rf example

      - name: Install dependencies
        run: dart pub get

      - name: Check format
        run: dart format --set-exit-if-changed .

      - name: Analyze
        run: dart analyze .

      - name: Run tests
        run: |
          dart pub global activate coverage 1.6.3
          dart test -j 1 -x pull-request-only --coverage=coverage && dart pub global run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.dart_tool/package_config.json --report-on=lib

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          min_coverage: 65
          path: coverage/lcov.info

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
